# Production Environment Configuration
spring:
    r2dbc:
        url: r2dbc:mysql://inventorydatabase.cpswwoukkbi2.ap-southeast-1.rds.amazonaws.com:3306/inventory
        username: admin
        password: mysqlInv2025
        pool:
            initial-size: 5
            max-size: 10
            max-idle-time: 30m

    flyway:
        enabled: true
        url: jdbc:mysql://inventorydatabase.cpswwoukkbi2.ap-southeast-1.rds.amazonaws.com:3306/inventory
        user: admin
        password: mysqlInv2025
        baseline-on-migrate: true

logging:
    level:
        com.quickcommerce.catalog: INFO
        org.springframework.r2dbc: WARN
        reactor.netty: WARN
        root: WARN
    file:
        name: /var/log/catalog-service/catalog-service.log

server:
    port: 8082
    netty:
        connection-timeout: 30s
        idle-timeout: 60s
