# Development Environment Configuration
spring:
    r2dbc:
        url: r2dbc:mysql://inventorydatabase.cpswwoukkbi2.ap-southeast-1.rds.amazonaws.com:3306/inventory
        username: admin
        password: mysqlInv2025

    flyway:
        enabled: true
        url: jdbc:mysql://inventorydatabase.cpswwoukkbi2.ap-southeast-1.rds.amazonaws.com:3306/inventory
        user: admin
        password: mysqlInv2025
        baseline-on-migrate: true

logging:
    level:
        com.quickcommerce.catalog: DEBUG
        org.springframework.r2dbc: DEBUG
        reactor.netty: DEBUG
