spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/inventory
    username: root
    password: root
  config:
    activate:
      on-profile: dev

# Override for local development
meilisearch:
  host: http://localhost:7700
  apiKey: masterKey

clients:
  catalog:
    url: http://localhost:8081  # Now pointing to product-service
  inventory:
    url: http://localhost:8081  # Now pointing to product-service2

# Detailed logging for development
logging:
  level:
    com.quickcommerce.search: DEBUG
    com.meilisearch: DEBUG
