spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/inventory
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/inventory
    user: root
    password: root

client:
  product-service:
    url: http://localhost:8081
  inventory-service:
    url: http://localhost:8081

logging:
  level:
    com.quickcommerce: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG
