# Production Environment Configuration
spring:
    r2dbc:
        url: r2dbc:mysql://inventorydatabase.cpswwoukkbi2.ap-southeast-1.rds.amazonaws.com:3306/inventory
        username: admin
        password: mysqlInv2025
        pool:
            initial-size: 5
            max-size: 10
            max-idle-time: 30m
    
    flyway:
        enabled: true
        url: jdbc:mysql://inventorydatabase.cpswwoukkbi2.ap-southeast-1.rds.amazonaws.com:3306/inventory
        user: admin
        password: mysqlInv2025
        baseline-on-migrate: true


logging:
    level:
        com.quickcommerce.inventory: INFO
        org.springframework.r2dbc: WARN
        org.springframework.security: WARN
        reactor.netty: WARN
        root: WARN
    file:
        name: /var/log/inventory-service/inventory-service.log

server:
    port: 8081
    netty:
        connection-timeout: 30s
        idle-timeout: 60s
        max-connections: 2000

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    tracing:
        sampling:
            probability: 0.1
