# Development Environment Configuration
spring:
    r2dbc:
        url: r2dbc:mysql://localhost:3306/inventory
        username: root
        password: root

    flyway:
        enabled: true
        url: jdbc:mysql://localhost:3306/inventory
        user: root
        password: root
        baseline-on-migrate: true


logging:
    level:
        com.quickcommerce.inventory: DEBUG
        org.springframework.r2dbc: DEBUG
        org.springframework.web.reactive: DEBUG
        reactor.netty: DEBUG

server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: "*"
